### PR TITLE
test_runner/performance: fix flush for NeonCompare

### PR DESCRIPTION
**Pull request by bayandin**
Fix performance tests:
```
AttributeError: 'NeonCompare' object has no attribute 'pageserver_http'
```

https://neon-github-public-dev.s3.amazonaws.com/reports/main/release/3713487584/index.html#categories/dcb49b9953ce76b182e54e96e1454755/b68ee72a188c0b38/

### CODE REVIEW

**Review by koivunej — APPROVED** [review]

**Review by hlinnaka — APPROVED** [review]
I broke that in c262390214109d46be2c230f1d52948e7134f76d. Sorry, thanks for the fix!
