### ISSUE TITLE
macOS build broken by https://github.com/neondatabase/neon/pull/11819

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#11860]
This broke the build on macOS:

```
error[E0412]: cannot find type `Error` in crate `tokio_epoll_uring`
   --> pageserver/src/virtual_file/io_engine.rs:318:72
    |
318 |     Fut: std::future::Future<Output = (T, Result<V, tokio_epoll_uring::Error<std::io::Error>>)>,
    |                                                                        ^^^^^ not found in `tokio_epoll_uring`
    |
```

_Originally posted by @erikgrinaker in https://github.com/neondatabase/neon/issues/11819#issuecomment-2862159324_
